name: deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secret.DOCKER_PASSWORD}}
    -
      name: Set uo Docker Build
      uses: docker/setup-buildx-action@v3
    -
      name: Build And Push
      uses: docker/build-push/action@v5
      with:
        context: .
        file: ./ecommerce-zimmer95/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce:latests
        
        
